services:
    app.notebook:
        class: AppBundle\Service\NotebookService
        arguments:
            - @doctrine.orm.entity_manager
            - @logger
            - @security.context
            - @security.token_storage

    app.note:
        class: AppBundle\Service\NoteService
        arguments:
            - @doctrine.orm.entity_manager
            - @logger
            - @security.context
            - @security.token_storage

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    security.access.note_voter:
        class:      AppBundle\Security\Authorization\Voter\NoteVoter
        public:     false
        tags:
           - { name: security.voter }