services:
    app.blog:
        class: AppBundle\Service\BlogService
        arguments:
            - @doctrine.orm.entity_manager
            - @logger

    app.post:
        class: AppBundle\Service\PostService
        arguments:
            - @doctrine.orm.entity_manager
            - @logger

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
